apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
        app: backend
  replicas: 1

  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.digitalocean.com/sec/backend:v1
          ports:
            - name: http
              containerPort: 3000
        
