apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: scan-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: scan-service
  imagePullSecrets:
    - name: registry-frong-testv1
  arguments:
    parameters:
    - name: target-domain
      value: ""
    - name: result-file
      value: ""
  serviceAccountName: argo
  templates:
  - name: scan-service
    steps:
    - - name: scan-dnsmap
        template: dnsmap
        arguments:
          parameters:
          - name: target-domain
            value: "{{workflow.parameters.target-domain}}"
          - name: result-file
            value: "{{workflow.parameters.result-file}}"
  #Services        
  - name: dnsmap
    inputs:
      parameters:
      - name: target-domain
      - name: result-file
    container:
      image: registry.digitalocean.com/frong-testv1/dnsmap:v1
      command: [./dnsmap, "{{inputs.parameters.target-domain}}", -r, ./result.txt]

