apiVersion: v1
kind: Namespace
metadata:
  name: webserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1

  template:
    metadata:
      name: webserver
      labels:
        app: webserver
    spec:
      #imagePullSecrets:
      # - name: registry-sec
      containers:
        - name: webserver
          image: registry.digitalocean.com/sec/webserver:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: webserver
spec:
  selector:
    matchLabels:
      app: express
  replicas: 1

  template:
    metadata:
      name: express
      labels:
        app: express
    spec:
      containers:
        - name: argo-middleware
          image: registry.digitalocean.com/sec/argo-middleware:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webserver
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1

  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.digitalocean.com/sec/backend:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
