apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hydra
spec:
  serviceAccountName: argo
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default
  entrypoint: hydra
  imagePullSecrets:
  - name: registry-sec
  arguments:
    parameters:
    - name: protocal
      value: "ssh"
    - name: endpoint
      value: "161.246.34.35"
  templates:
  - name: hydra
    inputs:
      parameters:
      - name: protocal
      - name: endpoint
    container:
      image: "registry.digitalocean.com/sec/hydra:latest"
      command: [sh, -c]
      args:
      - bash run.sh {{inputs.parameters.protocal}} {{inputs.parameters.endpoint}};
    outputs:
      artifacts:
      - name: hydra-log
        path: "/tmp/log"
        archive: 
          none: {}
      
