apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nmap
spec:
  serviceAccountName: argo
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default
  entrypoint: nmap
  imagePullSecrets:
  - name: registry-sec
  templates:
  - name: nmap
    inputs:
      artifacts:
      - name: dnsmap
        path: /mnt/dnsmap/dnsmap
    container:
      image: "registry.digitalocean.com/sec/nmap:v1"
      command: [sh, -c]
      args:
      - nmap -v -A -p- -oX /tmp/nmap2hydra.xml -oN /tmp/log -iL /mnt/dnsmap/dnsmap;
    outputs:
      artifacts:
      - name: nmap-log
        path: "/tmp/log"
        archive: 
          none: {}
      