apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: print-artifact
  namespace: argo
spec:
  serviceAccountName: argo
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default
  entrypoint: print
  arguments:
  templates:
    - name: print
      inputs:
        artifacts:
          - name: printout
            path: /tmp
            s3:
              key: "pawee/endpoint-test-5l7ht/log"
      container:
        image: alpine
        command: ['/bin/sh', '-c']
        args: ["ls /tmp; sleep 10"]

