apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  serviceAccountName: argo
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default
  entrypoint: test
  templates:
    - name: test
      dag:
        tasks:
          - name: generate
            template: whalesay
          - name: hydra
            dependencies: [generate]
            templateRef:
              name: hydra
              template: hydra
            arguments:
              parameters:
                - name: protocal-endpoint-port
                  value: "{{item}}"
            withParam: "{{tasks.generate.outputs.parameters.hello-param}}"
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args:
        - endpoint='[]' && echo -e $endpoint > /tmp/hello_world.txt
      outputs:
        parameters:
          - name: hello-param
            valueFrom:
              path: /tmp/hello_world.txt
