apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tool
spec:
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default
  entrypoint: test
  imagePullSecrets:
    - name: registry-sec
  arguments:
    parameters:
      - name: tool
        value: 'tool-name'
      - name: arg
        value: ''
  serviceAccountName: argo
  templates:
    - name: test
      steps:
        - - name: "{{workflow.parameters.tool}}"
            template: selected-tool
            arguments:
              parameters:
                - name: arg
                  value: "{{workflow.parameters.arg}}"

    #Services
    - name: selected-tool
      inputs:
        parameters: 
          - name: arg
      container:
        image: "registry.digitalocean.com/sec/{{workflow.parameters.tool}}:v1"
        command: [sh, -c]
        args: ["{{inputs.parameters.arg}}"]
      outputs:
        artifacts:
        - name: message
          path: "/tmp/"
          archive: 
            none: {}

