apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: validate-ip
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: validate-ip
  arguments:
    parameters:
    - name: endpoint
      value: ""  
  templates:
  - name: validate-ip
    inputs:
      parameters:
      - name: endpoint
    script:
      image: debian:9.4
      command: [bash]
      source: |                                         # Contents of the here-script
        regEx=^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ 
        ip={{inputs.parameters.endpoint}}

        if  [[ $ip =~ $regEx ]]; then 
          echo "true" 
        else 
          echo "false"  
        fi