apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hydra
  namespace: argo
spec:
  serviceAccountName: default
  entrypoint: hydra
  imagePullSecrets:
  - name: registry-sec
  arguments:
    parameters:
    - name: endpoint
      value: ""
    - name: protocol-port
      value: ""
    - name: protocol-endpoint
      value: "ssh://161.246.34.35:22"
    - name: company
      value: ""
  templates:
  - name: hydra
    inputs:
      parameters:
      - name: endpoint
      - name: protocol-port
      - name: protocol-endpoint
      - name: company
    container:
      image: "registry.digitalocean.com/sec/hydra:latest"
      command: [sh, -c]
      args:
      - bash run.sh "{{inputs.parameters.protocol-endpoint}}";
    outputs:
      artifacts:
      - name: hydra-log
        path: "/tmp/log" 
        archive: 
          none: {}
        s3:
          key: "{{inputs.parameters.company}}/{{workflow.name}}/{{inputs.parameters.endpoint}}/log/hydra/{{inputs.parameters.protocol-port}}.log"