apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nmap
  namespace: argo
spec:
  serviceAccountName: default
  # artifactRepositoryRef:
  #   configMap: artifact-repositories
  #   key: default
  entrypoint: nmap
  imagePullSecrets:
    - name: registry-sec
  arguments:
    parameters:
      - name: company
        value: ""
      - name: endpoint
        value: ""
  templates:
    - name: nmap
      inputs:
        parameters:
          - name: company
          - name: endpoint
        artifacts:
          - name: dnsmap
            path: /mnt/dnsmap/dnsmap
      container:
        image: "registry.digitalocean.com/sec/nmap:latest"
        command: [sh, -c]
        args:
          - bash run.sh
      outputs:
        parameters:
          - name: dnmp2hydra
            valueFrom:
              path: /tmp/nmap2hydra
              default: ""
        artifacts:
          - name: nmap-log
            path: "/tmp/log"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.company}}/{{workflow.name}}/{{inputs.parameters.endpoint}}/log/nmap/{{inputs.parameters.endpoint}}.log"
          - name: nmap-json
            path: "/nmap/data.json"
            archive:
              none: {}
            s3:
              key: "{{inputs.parameters.company}}/{{workflow.name}}/{{inputs.parameters.endpoint}}/log/nmap/{{inputs.parameters.endpoint}}.json"
