apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
  labels:
      app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
  labels:
      app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1

  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.digitalocean.com/sec/backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080