apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
  labels:
      app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1

  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      #imagePullSecrets:
      # - name: registry-sec
      containers:
        - name: frontend
          image: registry.digitalocean.com/sec/frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000