apiVersion: v1
kind: ConfigMap
metadata:
  # if you want to use this config map by default - name it "artifact-repositories"
  name: artifact-repositories
  annotations:
    # if you want to use a specific key, put that's key into this annotation
    workflows.argoproj.io/default-artifact-repository: default
data:
  default: |
    s3:
      endpoint: fra1.digitaloceanspaces.com
      bucket: csi
      keyFormat: argo/{{workflow.name}}/{{workflows.name}}
      accessKeySecret:
        name: artifact-key
        key: accessKey
      secretKeySecret:
        name: artifact-key
        key: secretKey
