apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  namespace: webserver
spec:
  imagePullSecrets:
    - name: registry-sec
  selector:
    matchLabels:
      app: debugger
  replicas: 1

  template:
    metadata:
      name: debugger
      labels:
        app: debugger
    spec:
      containers:
        - name: debugger
          image: registry.digitalocean.com/sec/nmap:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
