apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dnsmap
  namespace: argo
spec:
  serviceAccountName: default
  # artifactRepositoryRef:
  #   configMap: artifact-repositories
  #   key: default
  entrypoint: dnsmap
  imagePullSecrets:
  - name: registry-sec
  arguments:
    parameters:
    - name: domainName
      value: ""
    - name: company
      value: ""
    - name: podname
      value: ""
  templates:
  - name: dnsmap
    inputs:
      parameters:
      - name: domainName
      - name: company
      - name: podname
    container:
      image: "registry.digitalocean.com/sec/dnsmap:v1"
      command: [sh, -c]
      args:
      - ./dnsmap "{{inputs.parameters.domainName}}" -r /tmp/log && grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}" "/tmp/log" | sort | uniq > "/tmp/dnsmap2nmap" && [ -s /tmp/dnsmap2nmap ] || echo "{{inputs.parameters.domainName}}" > /tmp/dnsmap2nmap;
    outputs:
      parameters:
      - name: d2n
        valueFrom:
          path: "/tmp/dnsmap2nmap"
      artifacts:
      - name: dnsmap-log
        path: "/tmp/log"
        archive: 
          none: {}
        s3:
          key: "{{inputs.parameters.company}}/{{workflow.name}}/{{inputs.parameters.podname}}/log/dnsmap/{{pod.name}}.log"
      # - name: d2n
      #   path: "/tmp/dnsmap2nmap"
      #   archive:
      #     none: {}