apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: filter-upload
  namespace: argo
spec:
  serviceAccountName: default
  entrypoint: filter-upload
  imagePullSecrets:
    - name: registry-sec
  arguments:
    parameters:
      - name: company
        value: ""
      - name: workflowName
        value: ""
      - name: endpoint
        value: ""
  templates:
    - name: filter-upload
      inputs:
        parameters:
          - name: company
          - name: workflowName
          - name: endpoint
      steps:
        - - name: filter
            template: filter-template
            arguments:
              parameters:
                - name: company
                  value: "{{inputs.parameters.company}}"
                - name: workflowName
                  value: "{{inputs.parameters.workflowName}}"
                - name: endpoint
                  value: "{{inputs.parameters.endpoint}}"
        - - name: upload
            template: upload-template
            arguments:
              parameters:
                - name: workflowName
                  value: "{{inputs.parameters.workflowName}}"
              artifacts:
                - name: report-json
                  raw:
                    data: |
                      "{{steps.filter.outputs.parameters.output-json}}"

    #templates
    - name: filter-template
      inputs:
        parameters:
          - name: company
          - name: workflowName
          - name: endpoint
        artifacts:
          - name: log
            path: /mnt/log
            s3:
              key: "{{inputs.parameters.company}}/{{inputs.parameters.workflowName}}/{{inputs.parameters.endpoint}}/log"
      container:
        image: "registry.digitalocean.com/sec/filter:latest"
        command: [sh, -c]
        args:
          - ./run.sh
      outputs:
        parameters:
          - name: output-json
            valueFrom:
              path: "/tmp/report.json"

    - name: upload-template
      inputs:
        parameters:
          - name: workflowName
        artifacts:
          - name: report-json
            path: /mnt/report.json
      script:
        image: curlimages/curl:7.76.1
        command: [sh]
        source: |
          fileLocation=/mnt/report.json
          json=`cat /mnt/report.json`
          data=$(cat <<EOF
          {
            "scanid": "{{inputs.parameters.workflowName}}",
            "data": $json
          }
          EOF
          )
          echo $data > /mnt/report.json
          curl -X POST 'https://csi.cmkl.ac.th/api/uploadResult' \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data-binary "@$fileLocation"
