apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hydra
  namespace: argo
spec:
  serviceAccountName: default
  entrypoint: hydra
  imagePullSecrets:
  - name: registry-sec
  arguments:
    parameters:
    - name: protocal-endpoint
      value: "ssh://161.246.34.35:22"
    - name: company
      value: ""
  templates:
  - name: hydra
    inputs:
      parameters:
      - name: protocal-endpoint
      - name: company
    container:
      image: "registry.digitalocean.com/sec/hydra:latest"
      command: [sh, -c]
      args:
      - bash run.sh {{inputs.parameters.protocal-endpoint}};
    outputs:
      artifacts:
      - name: hydra-log
        path: "/tmp/log" 
        archive: 
          none: {}
        s3:
          key: log/{{inputs.parameters.company}}/{{workflow.name}}/{{pod.name}}/log